embed.embed_type_settings.oe_oembed_entities:
  type: mapping
  label: 'Schema for the entity oEmbed type'
  mapping:
    entity_type:
      type: string
      label: 'Entity type'
    bundles:
      type: sequence
      label: 'Bundles'
      sequence:
        type: string
        label: 'Bundle'
    entity_browser:
      type: string
      label: 'Entity browser'
    entity_browser_settings:
      type: mapping
      label: 'Entity browser settings'
      mapping:
        display_review:
          type: boolean
          label: 'Display review step'

oe_oembed.settings:
  type: config_object
  label: 'Configuration for the oe_oembed module.'
  mapping:
    resource_base_url:
      type: uri
      label: 'Base path for the oEmbed resource URL'
    service_url:
      type: uri
      label: 'oEmbed service URL'

core.entity_view_display.*.*.*.third_party.oe_oembed:
  type: mapping
  label: 'OpenEuropa oEmbed settings'
  mapping:
    embeddable:
      type: boolean
      label: 'Embeddable'
    inline:
      type: boolean
      label: 'Whether the embed should not be inline instead of a paragraph-based block'
